---
- name: Install macOS applications and utilities
  hosts: localhost
  gather_facts: no
  vars:
    homebrew_installed_packages:
      - fzf
      - zsh-syntax-highlighting
      - docker
      - docker-compose
      - trash
      - jsonpp
      - jq
      # - exa
      - z
      - neovim
      - alacritty
      - yqrashawn/goku/goku
      - nushell
      - bun
      


    homebrew_cask_packages:
      - 1password
      - alacrity
      - slack
      - tiles
      - keyboard-maestro
      - raycast
      - figma
      - miro
      - karabiner-elements

  tasks:
    - name: Add Homebrew tap for Goku
      homebrew_tap:
        name: yqrashawn/goku
        state: present

    - name: Install Homebrew packages
      homebrew:
        name: "{{ item }}"
        state: present
      loop: "{{ homebrew_installed_packages }}"

    - name: Install Homebrew Cask applications
      homebrew_cask:
        name: "{{ item }}"
        state: present
      loop: "{{ homebrew_cask_packages }}"